const gulp = require('gulp');
const rename = require("gulp-rename");
const minify = require('gulp-html-minifier');

module.exports = (path) => {
  return gulp.src([`${path}/**.html`, `!${path}/**.min.html`])
  .pipe(minify({
    collapseWhitespace: true,
    includeAutoGeneratedTags: false,
    minifyCSS: true,
    minifyJS: true,
    removeComments: true,
    removeEmptyAttributes: true,
  })).on('error', (e) => {
    console.error(e.toString());
    this.emit("end");
  }).pipe(rename({
      extname: '.min.html'
  })).pipe(gulp.dest(path))
}
